# Generated by Django 2.0.4 on 2018-04-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180423_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Color'),
        ),
    ]
